remote_theme: andrewbanchich/forty-jekyll-theme
title: Rachel Radke | Portfolio
subtitle: Data Analyst | Software Engineer | Machine Learning Engineer
email: rachelcradke@gmail.com
description: Examples of my technical projects
baseurl: "" # leave empty
url: "https://rachelradical.github.io"

tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# Social settings
github_url: https://github.com/rachelradical
LinkedIn: https://www.linkedin.com/in/rachel-c-radke

